# Generated by Django 3.1.13 on 2021-09-24 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210924_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinputvalue',
            name='search_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 19, 36, 10, 373650, tzinfo=utc)),
        ),
    ]
