# Generated by Django 3.1.13 on 2021-09-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210924_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinputvalue',
            name='search_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
