# Generated by Django 3.1.13 on 2021-09-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210924_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinputvalue',
            old_name='number_list',
            new_name='input_values',
        ),
        migrations.RenameField(
            model_name='userinputvalue',
            old_name='search_date',
            new_name='timestamp',
        ),
    ]
